### ISSUE TITLE
Rails 4.1 compatibility?

### ISSUE THREAD

**Issue by calebhaye** [muratguzel/letsrate#76]
Doesn't seem to work with Rails 4.1 ... tried 1.0.8 and latest

```
$ rails g letsrate User
  create  app/assets/javascripts/jquery.raty.js
  create  app/assets/images/star-on.png
  create  app/assets/images/star-off.png
  create  app/assets/images/star-half.png
  create  app/assets/javascripts/letsrate.js.erb
  create  app/controllers/rater_controller.rb
  create  app/models/rate.rb
  create  app/models/rating_cache.rb
   route  match '/rate' => 'rater#create', :as => 'rate'
/Users/foo/.rvm/gems/ruby-2.1.2@bar/gems/letsrate-1.0.8/lib/generators/letsrate/letsrate_generator.rb:36:in `create_migration': wrong number of arguments (3 for 0) (ArgumentError)
from /Users/foo/.rvm/gems/ruby-2.1.2@bar/gems/railties-4.1.1/lib/rails/generators/migration.rb:63:in `migration_template'
from /Users/foo/.rvm/gems/ruby-2.1.2@bar/gems/letsrate-1.0.8/lib/generators/letsrate/letsrate_generator.rb:32:in `create_cacheable_migration'
```

**Comment by alfredayibonte** [comment]
thanks @sungwoncho

**Comment by microweb10** [comment]
FYI
If you don't want to use another gem and make this one compatible with Rails 4. Just rename the method  create_migration (line 37 in the file [lib/generators/letsrate/letsrate_generator.rb](https://github.com/muratguzel/letsrate/blob/master/lib/generators/letsrate/letsrate_generator.rb)) to something else.

Change this
```ruby
def create_migration
  migration_template "migration.rb", "db/migrate/create_rates.rb"
end
```


To this
```ruby
def create_rates_migration
  migration_template "migration.rb", "db/migrate/create_rates.rb"
end
```

**Comment by sunil-netsol** [comment]
Worked for me.

**Comment by Daham94** [comment]
plz tell me how to access this file

**Comment by Daham94** [comment]
how to access this file
/Users/daham/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nifty-generators-0.4.6/lib/generators/nifty/scaffold/scaffold_generator.rb
