### ISSUE TITLE
`create_migration': wrong number of arguments (3 for 0) (ArgumentError)

### ISSUE THREAD

**Issue by wonderer007** [muratguzel/letsrate#85]
when i run following command `rails g letsrate user` it give this error

/home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/letsrate-1.0.9/lib/generators/letsrate/letsrate_generator.rb:37:in `create_migration': wrong number of arguments (3 for 0) (ArgumentError)
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/railties-4.2.0/lib/rails/generators/migration.rb:63:in`migration_template'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/letsrate-1.0.9/lib/generators/letsrate/letsrate_generator.rb:33:in `create_cacheable_migration'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`block in invoke_all'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`map'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/thor-0.19.1/lib/thor/group.rb:232:in`dispatch'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/railties-4.2.0/lib/rails/generators.rb:157:in`invoke'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/railties-4.2.0/lib/rails/commands/generate.rb:13:in `<top (required)>'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in`require'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in`load_dependency'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:123:in`require_command!'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:50:in`generate'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /home/office/.rvm/gems/ruby-2.2.1@speaker-replay/gems/railties-4.2.0/lib/rails/commands.rb:17:in`<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in`<main>'

**Comment by ThomasLamiraud** [comment]
Solved in #76
